strategy:
  name: gpt       # options: sma, gpt
  params:
    context_hours: 3       # number of hours of OHLCV to include in the prompt
    provider: openai       # options: mock, openai
    show_prompt: true      # show the prompt sent to the LLM
    mode: live             # options: backtest, live


data:
  symbol: BTCUSDT
  timeframe: 15m
  lookback: 200   # optional, default=200
  start: "2022-09-01"
  end: "2025-09-01"




